version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-chat-api
    ports:
      - "8000:8000"
    environment:
      - GIN_MODE=release
      - GROQ_API_KEY=${GROQ_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - app-network


networks:
  app-network:
    driver: bridge 